_BASE_: ../Base-bagtricks.yml

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

OUTPUT_DIR: logs/market1501/bagtricks_R50

MODEL:
  HEADS:
    NUM_CLASSES: 751

SOLVER:
  AMP:
    ENABLED: False